//! Codegen: emit `CONTRACT_LINEAGE` / `DELEGATE_LINEAGE` consts into `$OUT_DIR`.

use std::path::{Path, PathBuf};

use crate::error::BuildError;
use crate::registry::Registry;

/// Start a codegen builder.
///
/// ```no_run
/// // in build.rs:
/// freenet_migrate_build::codegen()
///     .registry("legacy.toml")
///     .emit()
///     .unwrap();
/// // then in the crate: include!(concat!(env!("OUT_DIR"), "/lineage.rs"));
/// ```
pub fn codegen() -> Codegen {
    Codegen::default()
}

/// Builder for the generated lineage consts.
#[derive(Debug, Clone, Default)]
pub struct Codegen {
    registry_path: Option<PathBuf>,
    out_file: Option<String>,
    contract_const: Option<String>,
    delegate_const: Option<String>,
    crate_path: Option<String>,
}

impl Codegen {
    /// Path to the `legacy.toml` registry.
    pub fn registry(mut self, path: impl Into<PathBuf>) -> Self {
        self.registry_path = Some(path.into());
        self
    }

    /// Output file name within `$OUT_DIR` (default `lineage.rs`).
    pub fn out_file(mut self, name: impl Into<String>) -> Self {
        self.out_file = Some(name.into());
        self
    }

    /// Name of the emitted contract const (default `CONTRACT_LINEAGE`). Set this
    /// to alias to an existing name (e.g. River's `LEGACY_ROOM_CONTRACT_...`).
    pub fn contract_const_name(mut self, name: impl Into<String>) -> Self {
        self.contract_const = Some(name.into());
        self
    }

    /// Name of the emitted delegate const (default `DELEGATE_LINEAGE`).
    pub fn delegate_const_name(mut self, name: impl Into<String>) -> Self {
        self.delegate_const = Some(name.into());
        self
    }

    /// Path to the `freenet-migrate` crate in the consumer (default
    /// `::freenet_migrate`). Override if the consumer re-exports it elsewhere.
    pub fn crate_path(mut self, path: impl Into<String>) -> Self {
        self.crate_path = Some(path.into());
        self
    }

    /// Render the generated Rust source as a string (pure; no I/O beyond reading
    /// the registry file). Useful for tests.
    pub fn generate_string(&self) -> Result<String, BuildError> {
        let path = self.registry_path.as_ref().ok_or(BuildError::NoRegistry)?;
        let registry = Registry::from_path(path)?;
        self.render(&registry)
    }

    /// Render from an already-parsed registry (no file I/O). Validates first.
    pub fn render(&self, registry: &Registry) -> Result<String, BuildError> {
        registry.validate()?;
        let crate_path = self.crate_path.as_deref().unwrap_or("::freenet_migrate");
        let contract_const = self.contract_const.as_deref().unwrap_or("CONTRACT_LINEAGE");
        let delegate_const = self.delegate_const.as_deref().unwrap_or("DELEGATE_LINEAGE");

        let mut out = String::new();
        out.push_str("// @generated by freenet-migrate-build — do not edit.\n\n");

        out.push_str(&format!(
            "pub const {contract_const}: &[{crate_path}::ContractLineageEntry] = &[\n"
        ));
        for row in &registry.contract {
            out.push_str(&format!(
                "    {crate_path}::ContractLineageEntry {{ generation: {}u32, code_hash: {}, note: {} }},\n",
                row.generation,
                rust_str(&row.code_hash),
                rust_str(&row.note),
            ));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "pub const {delegate_const}: &[{crate_path}::DelegateLineageEntry] = &[\n"
        ));
        for row in &registry.delegate {
            out.push_str(&format!(
                "    {crate_path}::DelegateLineageEntry {{ generation: {}u32, code_hash: {}, delegate_key: {}, note: {} }},\n",
                row.generation,
                rust_str(&row.code_hash),
                rust_str(&row.delegate_key),
                rust_str(&row.note),
            ));
        }
        out.push_str("];\n");

        Ok(out)
    }

    /// Read the registry, render the consts, and write them into `$OUT_DIR`.
    /// Emits `cargo:rerun-if-changed` for the registry. Returns the output path.
    pub fn emit(self) -> Result<PathBuf, BuildError> {
        let out_dir =
            std::env::var("OUT_DIR").map_err(|_| BuildError::Env("OUT_DIR not set".to_string()))?;
        let file = self
            .out_file
            .clone()
            .unwrap_or_else(|| "lineage.rs".to_string());
        let dest = Path::new(&out_dir).join(&file);
        let code = self.generate_string()?;
        std::fs::write(&dest, code)
            .map_err(|e| BuildError::Io(format!("writing {}: {e}", dest.display())))?;
        if let Some(reg) = &self.registry_path {
            println!("cargo:rerun-if-changed={}", reg.display());
        }
        Ok(dest)
    }
}

/// Format `s` as a Rust string literal (quotes + escaped body).
fn rust_str(s: &str) -> String {
    format!("\"{}\"", s.escape_default())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::{ContractRow, DelegateRow};

    fn b58(b: [u8; 32]) -> String {
        bs58::encode(b)
            .with_alphabet(bs58::Alphabet::BITCOIN)
            .into_string()
    }

    fn sample_registry() -> Registry {
        Registry {
            contract: vec![
                ContractRow {
                    generation: 0,
                    code_hash: b58([1; 32]),
                    note: "v1".to_string(),
                },
                ContractRow {
                    generation: 1,
                    code_hash: b58([2; 32]),
                    note: String::new(),
                },
            ],
            delegate: vec![DelegateRow {
                generation: 0,
                code_hash: b58([4; 32]),
                delegate_key: b58([3; 32]),
                note: "delegate v1".to_string(),
            }],
        }
    }

    #[test]
    fn renders_default_const_names_and_entries() {
        let reg = sample_registry();
        let out = codegen().render(&reg).unwrap();
        assert!(out.contains(
            "pub const CONTRACT_LINEAGE: &[::freenet_migrate::ContractLineageEntry] = &["
        ));
        assert!(out.contains(
            "pub const DELEGATE_LINEAGE: &[::freenet_migrate::DelegateLineageEntry] = &["
        ));
        assert!(out.contains(&format!(
            "::freenet_migrate::ContractLineageEntry {{ generation: 0u32, code_hash: \"{}\", note: \"v1\" }},",
            b58([1; 32])
        )));
        assert!(out.contains(&format!(
            "::freenet_migrate::DelegateLineageEntry {{ generation: 0u32, code_hash: \"{}\", delegate_key: \"{}\", note: \"delegate v1\" }},",
            b58([4; 32]),
            b58([3; 32])
        )));
    }

    #[test]
    fn honors_alias_names_and_crate_path() {
        let reg = sample_registry();
        let out = codegen()
            .contract_const_name("LEGACY_ROOM_CONTRACT_CODE_HASHES")
            .delegate_const_name("LEGACY_DELEGATES")
            .crate_path("crate::migrate")
            .render(&reg)
            .unwrap();
        assert!(out.contains(
            "pub const LEGACY_ROOM_CONTRACT_CODE_HASHES: &[crate::migrate::ContractLineageEntry] = &["
        ));
        assert!(out.contains("pub const LEGACY_DELEGATES: &[crate::migrate::DelegateLineageEntry]"));
        assert!(!out.contains("::freenet_migrate::"));
    }

    #[test]
    fn escapes_note_string_literals() {
        let reg = Registry {
            contract: vec![ContractRow {
                generation: 0,
                code_hash: b58([1; 32]),
                note: "quote \" and backslash \\ here".to_string(),
            }],
            delegate: vec![],
        };
        let out = codegen().render(&reg).unwrap();
        assert!(out.contains(r#"note: "quote \" and backslash \\ here""#));
    }

    #[test]
    fn render_fails_on_invalid_registry() {
        let reg = Registry {
            contract: vec![ContractRow {
                generation: 0,
                code_hash: "not-32-bytes".to_string(),
                note: String::new(),
            }],
            delegate: vec![],
        };
        assert!(codegen().render(&reg).is_err());
    }

    #[test]
    fn generate_string_requires_a_registry_path() {
        assert_eq!(
            codegen().generate_string().unwrap_err(),
            BuildError::NoRegistry
        );
    }
}
