// @generated by freenet-migrate-build — do not edit.

pub const CONTRACT_LINEAGE: &[::freenet_migrate::ContractLineageEntry] = &[
    ::freenet_migrate::ContractLineageEntry { generation: 0u32, code_hash: [65, 93, 3, 145, 108, 204, 221, 202, 5, 125, 52, 60, 224, 245, 200, 220, 137, 96, 98, 33, 208, 178, 96, 243, 223, 199, 52, 79, 100, 221, 91, 56], note: "V1: quote \" and backslash \\ (2025-08-11)" },
    ::freenet_migrate::ContractLineageEntry { generation: 1u32, code_hash: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], note: "multi\nline note" },
];

pub const DELEGATE_LINEAGE: &[::freenet_migrate::DelegateLineageEntry] = &[
    ::freenet_migrate::DelegateLineageEntry { generation: 1u32, code_hash: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9], delegate_key: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8], irregular_key: true, note: "V1: pre-standard recorded key" },
    ::freenet_migrate::DelegateLineageEntry { generation: 2u32, code_hash: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], delegate_key: [177, 205, 99, 91, 13, 202, 223, 9, 196, 86, 52, 42, 63, 37, 4, 191, 132, 238, 78, 166, 122, 192, 174, 72, 133, 53, 78, 1, 251, 173, 192, 77], irregular_key: false, note: "V2: regular empty-params row" },
    ::freenet_migrate::DelegateLineageEntry { generation: 3u32, code_hash: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], delegate_key: [26, 127, 202, 236, 5, 92, 10, 97, 196, 244, 249, 79, 93, 219, 132, 86, 59, 61, 134, 164, 55, 108, 249, 68, 164, 171, 170, 40, 205, 114, 104, 75], irregular_key: false, note: "V3: non-empty params row" },
];

pub const FIXTURE_CONTRACT_HASHES: &[[u8; 32]] = &[
    // V1: quote " and backslash \ (2025-08-11)
    [65, 93, 3, 145, 108, 204, 221, 202, 5, 125, 52, 60, 224, 245, 200, 220, 137, 96, 98, 33, 208, 178, 96, 243, 223, 199, 52, 79, 100, 221, 91, 56],
    // multi line note
    [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
];

pub const FIXTURE_DELEGATE_PAIRS: &[([u8; 32], [u8; 32])] = &[
    // V1: pre-standard recorded key
    ([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8], [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]),
    // V2: regular empty-params row
    ([177, 205, 99, 91, 13, 202, 223, 9, 196, 86, 52, 42, 63, 37, 4, 191, 132, 238, 78, 166, 122, 192, 174, 72, 133, 53, 78, 1, 251, 173, 192, 77], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]),
    // V3: non-empty params row
    ([26, 127, 202, 236, 5, 92, 10, 97, 196, 244, 249, 79, 93, 219, 132, 86, 59, 61, 134, 164, 55, 108, 249, 68, 164, 171, 170, 40, 205, 114, 104, 75], [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]),
];

